---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  chef_license: accept

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/default

platforms:
  - name: centos-6-docker
    driver_config:
      image: centos:6
      run_command: '/sbin/init'
      provision_command:
        # For Inspec
        - yum install -y net-tools
  - name: centos-7-docker
    driver_config:
      image: centos:7
      run_command: '/usr/lib/systemd/systemd'
      provision_command:
        - systemctl set-default multi-user.target
        # For Inspec
        - yum install -y net-tools
  - name: debian-8-docker
    driver_config:
      image: debian:8
      disable_upstart: false
      run_command: '/sbin/init'
      provision_command:
        - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
        - apt-get install -y locales && locale-gen en_US.UTF-8
        # Netstat for Inspec
        - apt-get install -y net-tools
  - name: debian-9-docker
    driver_config:
      image: debian:9
      disable_upstart: false
      run_command: '/lib/systemd/systemd'
      provision_command:
        - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
        - apt-get install -y locales && locale-gen en_US.UTF-8
        # Netstat for Inspec
        - apt-get install -y net-tools
        # gnupg for Chef
        - apt-get install -y gnupg
  - name: ubuntu-14.04-docker
    driver_config:
      image: ubuntu-upstart:14.04
      disable_upstart: false
      run_command: '/sbin/init'
      provision_command:
        # Netstat for Serverspec
        - apt-get install -y net-tools
  - name: ubuntu-16.04-docker
    driver_config:
      image: ubuntu:16.04
      run_command: '/sbin/init'
      provision_command:
        - apt-get install -y locales && locale-gen en_US.UTF-8
        # For systemd
        - systemctl set-default multi-user.target
        # Netstat for Inspec
        - apt-get install -y net-tools
  - name: ubuntu-18.04-docker
    driver_config:
      image: ubuntu:18.04
      run_command: '/sbin/init'
      provision_command:
        - apt-get install -y locales && locale-gen en_US.UTF-8
        # For systemd
        - systemctl set-default multi-user.target
        # Netstat for Inspec
        - apt-get install -y net-tools

suites:
  - name: chef-13
    run_list:
      - recipe[testrig]
    provisioner:
      product_name: chef
      product_version: 13
    attributes:
      prometheus_exporters:
        node:
          collectors_disabled: ["wifi"]
  - name: chef-14
    run_list:
      - recipe[testrig]
    provisioner:
      product_name: chef
      product_version: 14
    attributes:
      prometheus_exporters:
        node:
          collectors_disabled: ["wifi"]
  - name: chef-15
    run_list:
      - recipe[testrig]
    provisioner:
      product_name: chef
      product_version: 15
    attributes:
      prometheus_exporters:
        node:
          collectors_disabled: ["wifi"]
