LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Naming/FileName:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
UnusedBlockArgument:
  Enabled: false
